language: python
python:
- "3.6.5"
services: postgresql

env:
  global:
  # - DJANGO="x.y.z"
  - DJANGO_SETTINGS_MODULE="post_registration.settings"
  - PYTHONPATH="/home/travis/build/evbeda/post-registration"
  - PIP_USE_MIRRORS=true

install:
- pip install -r requirements.txt

before_script:
- psql -c 'create database travisdb;' -U postgres

script:
- python manage.py migrate
- coverage run manage.py test
- sonar-scanner

after_success:
- coveralls
sudo: false
cache: pip
dist: trusty
addons:
  sonarcloud:
    organization: "leonardxfce-github"
    token:
      secure: $SONAR_TOKEN