language: python
python:
- "3.6.5"
services: postgresql

env:
  global:
  - DJANGO_SETTINGS_MODULE="post_registration.settings"
  - PYTHONPATH="/home/travis/build/evbeda/post-registration"
  - PIP_USE_MIRRORS=true

install:
- pip install -r requirements.txt

before_script:
- psql -c 'create database travisdb;' -U postgres

script:
- python manage.py migrate
- coverage erase
- coverage run manage.py test
- coverage xml -i
- coveralls
- which pylint
- sonar-scanner
sudo: false

cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.sonar
  - $HOME/jvm
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/fileHashes/
- rm -fr $HOME/.gradle/caches/*/scripts/
dist: trusty
addons:
  sonarcloud:
    organization: "leonardxfce-github"
    token:
      secure: $SONAR_TOKEN
