from django.conf.urls import url

from documentsManager.utils import select_event, accept_webhook
from .views import (
    EventsView,
    DocFormView,
    DocsView,
    HomeView,
    FileDocUpdate,
    TextDocUpdate,
    FileDocDelete,
    TextDocDelete,
    LandingView,
    SuccessView,
    SignUpView,
    EvaluatorList,
    EvaluatorCreate,
    EvaluatorUpdate,
    EvaluatorDelete,
    SubmissionsList,
    AcceptInvitationView,
    DeclineInvitationView,
    ReviewView,
    SubmissionView,
    ResultCreate,
)

urlpatterns = [
    url(r'accept-invitation/(?P<invitation_code>[\w\-]+)/$',
        AcceptInvitationView.as_view(),
        name='accept-invitation'
        ),
    url(r'decline-invitation/(?P<invitation_code>[\w\-]+)/$',
        DeclineInvitationView.as_view(),
        name='decline-invitation'
        ),
    url(
        r'landing/(?P<event_id>\d+)/(?P<code>[\w\-]+)$',
        LandingView.as_view(),
        name='landing'
    ),
    url(
        r'landing/(?P<event_id>\d+)/preview/$',
        LandingView.as_view(),
        name='preview'
    ),
    url(
        r'success/$',
        SuccessView.as_view(),
        name='success'
    ),
    url(
        r'doc_form/(?P<event_id>\d+)/$',
        DocFormView.as_view(),
        name='doc_form'
    ),
    url(
        r'^event/(?P<event_id>\d+)/evaluator/add/$',
        EvaluatorCreate.as_view(),
        name='evaluator_create'
    ),
    url(
        r'^event/(?P<event_id>\d+)/evaluator/(?P<pk>\d+)/edit/$',
        EvaluatorUpdate.as_view(),
        name='evaluator_update'
    ),
    url(
        r'^event/(?P<event_id>\d+)/evaluator/(?P<evaluator_id>\d+)/delete/$',
        EvaluatorDelete.as_view(),
        name='evaluator_delete'
    ),
    url(
        r'^event/(?P<event_id>\d+)/evaluators/$',
        EvaluatorList.as_view(),
        name='evaluators'
    ),
    url(
        r'^event/(?P<event_id>\d+)/docs/file/(?P<pk>\d+)/edit/$',
        FileDocUpdate.as_view(),
        name="edit-filedoc"
    ),
    url(
        r'^event/(?P<event_id>\d+)/docs/text/(?P<pk>\d+)/edit/$',
        TextDocUpdate.as_view(),
        name="edit-textdoc"
    ),
    url(
        r'^event/(?P<event_id>\d+)/docs/file/(?P<pk>\d+)/delete/$',
        FileDocDelete.as_view(),
        name="delete-filedoc"
    ),
    url(
        r'^event/(?P<event_id>\d+)/docs/text/(?P<pk>\d+)/delete/$',
        TextDocDelete.as_view(),
        name="delete-textdoc"
    ),
    url(
        r'event/(?P<event_id>\d+)/docs/$',
        DocsView.as_view(),
        name='docs'
    ),
    url(
        r'events/$',
        EventsView.as_view(),
        name='events'
    ),
    url(
        r'events/(?P<eb_event_id>\d+)/$',
        select_event,
        name='events'
    ),
    url(
        r'event/(?P<event_id>\d+)/submissions/(?P<submission_id>\d+)/close/$',
        ResultCreate.as_view(),
        name='close_submission'
    ),
    url(
        r'event/(?P<event_id>\d+)/submissions/(?P<submission_id>\d+)/$',
        SubmissionView.as_view(),
        name='submission'
    ),
    url(
        r'event/(?P<event_id>\d+)/submissions/$',
        SubmissionsList.as_view(),
        name='submissions'
    ),
    url(
        r'event/(?P<event_id>\d+)/submissions/(?P<submission_id>\d+)/review/$',
        ReviewView.as_view(),
        name='review'
    ),
    url(
        r'signup/$',
        SignUpView.as_view(),
        name='signup'
    ),
    url(
        r'^webhook-point/',
        accept_webhook,
        name='accept_webhook'
    ),
    url(
        r'^$',
        HomeView.as_view(),
        name='home'
    )
]
