# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedoc',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='textdoc',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
