# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='event',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='documentsManager.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_submission',
            field=models.DateField(blank=True, null=True),
        ),
    ]
