# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-31 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluator',
            name='events',
        ),
        migrations.RemoveField(
            model_name='evaluator',
            name='state',
        ),
    ]
