# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-31 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0002_auto_20181031_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluatorEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentsManager.Evaluator')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentsManager.Event')),
            ],
            options={
                'db_table': 'EvaluatorEvent',
            },
        ),
        migrations.AddField(
            model_name='evaluator',
            name='event',
            field=models.ManyToManyField(through='documentsManager.EvaluatorEvent', to='documentsManager.Event'),
        ),
    ]
