# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0002_auto_20180927_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eb_event_id',
            field=models.TextField(unique=True),
        ),
    ]
