# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0002_auto_20181106_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documentsManager.Event'),
            preserve_default=False,
        ),
    ]
