# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0002_auto_20181004_1403'),
        ('documentsManager', '0002_auto_20181004_1420'),
    ]

    operations = [
    ]
