# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-01 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0003_auto_20180928_1413'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doc',
            table='Doc',
        ),
        migrations.AlterModelTable(
            name='event',
            table='Event',
        ),
        migrations.AlterModelTable(
            name='filetype',
            table='FileType',
        ),
    ]
