# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-08 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0003_submission_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendeeCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=512)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
