# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0003_submission_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluatorevent',
            old_name='state',
            new_name='status',
        ),
    ]
