# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0003_auto_20181031_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesubmission',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
