# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0004_remove_textdoc_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_submission',
            field=models.DateField(null=True),
        ),
    ]
