# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0004_evaluatorevent_invitation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluatorevent',
            name='invitation_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
