# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 13:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0004_remove_textdoc_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedoc',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='textdoc',
            name='max',
            field=models.IntegerField(default=500, validators=[django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='textdoc',
            name='min',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
