# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-08 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0004_auto_20181107_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date_time',
        ),
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='init_submission',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
