# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-02 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0004_event_organizer'),
        ('documentsManager', '0004_filesubmission_state'),
    ]

    operations = [
    ]
