# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-08 13:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0004_auto_20181107_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_evaluation',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_evaluation',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
