# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-02 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0005_merge_20181102_1305'),
        ('documentsManager', '0005_auto_20181101_1515'),
    ]

    operations = [
    ]
