# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-08 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0005_auto_20181108_1816'),
        ('documentsManager', '0006_auto_20181108_1347'),
    ]

    operations = [
    ]
