# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0006_auto_20181010_1251'),
        ('documentsManager', '0005_auto_20181009_1453'),
    ]

    operations = [
    ]
