# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 18:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0006_merge_20181102_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('aproved', models.BooleanField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='filesubmission',
            name='EB_user_id',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evaluator',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='review',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentsManager.Evaluator'),
        ),
        migrations.AddField(
            model_name='review',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentsManager.Event'),
        ),
    ]
