# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-08 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0007_merge_20181108_1828'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([('evaluator', 'submission')]),
        ),
    ]
