# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 18:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0008_auto_20181010_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('date', models.DateField(default=datetime.date.today)),
                ('file_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentsManager.FileDoc')),
            ],
            options={
                'db_table': 'FileSubmission',
            },
        ),
        migrations.AlterField(
            model_name='textdoc',
            name='measure',
            field=models.CharField(choices=[('Words', 'Words'), ('Characters', 'Characters')], default='Words', max_length=5),
        ),
    ]
