# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0008_auto_20181010_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('events', models.ManyToManyField(to='documentsManager.Event')),
            ],
            options={
                'db_table': 'Evaluator',
            },
        ),
        migrations.AlterField(
            model_name='textdoc',
            name='measure',
            field=models.CharField(choices=[('Words', 'Words'), ('Characters', 'Characters')], default='Words', max_length=5),
        ),
    ]
