# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0008_auto_20181010_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textdoc',
            name='measure',
            field=models.CharField(choices=[('Words', 'Words'), ('Characters', 'Characters')], default='Words', max_length=10),
        ),
    ]
