# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 02:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0008_merge_20181109_0102'),
        ('documentsManager', '0008_auto_20181108_2307'),
    ]

    operations = [
    ]
