# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-13 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0009_merge_20181112_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Attendee',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='attendeecode',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documentsManager.Event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendeecode',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
        migrations.AlterModelTable(
            name='userwebhook',
            table='UserWebhook',
        ),
        migrations.AddField(
            model_name='attendeecode',
            name='attendee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documentsManager.Attendee'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='attendeecode',
            unique_together=set([('attendee', 'event')]),
        ),
    ]
