# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0010_textdoc_description'),
        ('documentsManager', '0009_auto_20181025_1826'),
    ]

    operations = [
    ]
