# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0010_textdoc_description'),
        ('documentsManager', '0009_auto_20181023_1720'),
    ]

    operations = [
    ]
