# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-15 17:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0010_auto_20181113_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name=datetime.datetime(2018, 11, 15, 17, 57, 40, 607040))),
                ('aproved', models.BooleanField(unique=True)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'Result',
            },
        ),
        migrations.RemoveField(
            model_name='submission',
            name='eb_user_id',
        ),
        migrations.AddField(
            model_name='attendee',
            name='eb_user_id',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='attendee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documentsManager.Attendee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documentsManager.Submission'),
        ),
    ]
