# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-15 20:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0011_auto_20181115_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='date_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 11, 15, 20, 1, 37, 689601)),
        ),
    ]
