# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0011_merge_20181023_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluator',
            name='state',
            field=models.CharField(choices=[('pending', 'Waiting for acceptance'), ('active', 'Active'), ('inactive', 'Inactive')], default='pending', max_length=20),
        ),
    ]
