# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-26 20:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0011_auto_20181115_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='justification',
        ),
        migrations.AlterField(
            model_name='result',
            name='date_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 11, 26, 20, 8, 37, 204653)),
        ),
        migrations.AlterField(
            model_name='review',
            name='aproved',
            field=models.BooleanField(),
        ),
    ]
