# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 20:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0012_auto_20181115_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='date_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 11, 16, 20, 2, 17, 495456)),
        ),
        migrations.AlterField(
            model_name='review',
            name='aproved',
            field=models.BooleanField(),
        ),
    ]
