# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-27 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0012_auto_20181126_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='comment',
            new_name='justification',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='aproved',
            new_name='approved',
        ),
        migrations.RemoveField(
            model_name='result',
            name='aproved',
        ),
        migrations.AddField(
            model_name='result',
            name='approved',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='result',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='result',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentsManager.Submission'),
        ),
    ]
