# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentsManager', '0012_auto_20181024_1241'),
        ('documentsManager', '0011_merge_20181025_1834'),
    ]

    operations = [
    ]
